toDo/config/routes.rb
Rails.application.routes.draw do
  root 'things_to_dos#index'
  resources :things_to_dos

end

toDo/app/models/things_to_do.rb
class ThingsToDo < ActiveRecord::Base
end

toDo/app/controllers/things_to_dos_controller.rb
class ThingsToDosController < ApplicationController
  before_action :set_things_to_do, only: [:show, :edit, :update, :destroy]

  # GET /things_to_dos
  # GET /things_to_dos.json
  def index
    @things_to_dos = ThingsToDo.all
  end

  # GET /things_to_dos/1
  # GET /things_to_dos/1.json
  def show
  end

  # GET /things_to_dos/new
  def new
    @things_to_do = ThingsToDo.new
  end

  # GET /things_to_dos/1/edit
  def edit
  end

  # POST /things_to_dos
  # POST /things_to_dos.json
  def create
    @things_to_do = ThingsToDo.new(things_to_do_params)

    respond_to do |format|
      if @things_to_do.save
        format.html { redirect_to @things_to_do, notice: 'Things to do was successfully created.' }
        format.json { render :show, status: :created, location: @things_to_do }
      else
        format.html { render :new }
        format.json { render json: @things_to_do.errors, status: :unprocessable_entity }
      end
    end
    # @things_to_do.save
  end

  # PATCH/PUT /things_to_dos/1
  # PATCH/PUT /things_to_dos/1.json
  def update
    respond_to do |format|
      if @things_to_do.update(things_to_do_params)
        format.html { redirect_to @things_to_do, notice: 'Things to do was successfully updated.' }
        format.json { render :show, status: :ok, location: @things_to_do }
      else
        format.html { render :edit }
        format.json { render json: @things_to_do.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things_to_dos/1
  # DELETE /things_to_dos/1.json
  def destroy
    @things_to_do.destroy
    respond_to do |format|
      format.html { redirect_to things_to_dos_url, notice: 'Things to do was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_things_to_do
      @things_to_do = ThingsToDo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def things_to_do_params
      params.require(:things_to_do).permit(:thing, :description, :done)
    end
end

toDo/app/helpers/things_to_dos_helper.rb
module ThingsToDosHelper
end

toDo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- our angular app -->
<div class="container">

<body ng-app="ToDoApp" ng-controller="task">
  <h1>To Do List</h1>
  <!-- 2 way data binding -->
  Task: <input type="text" ng-model="thing"><br>
  Description: <input type="text" ng-model="description"><br>
  <input type="text" ng-model="done" hidden >

  <button ng-click="addListItem()">Add To List</button>
<!-- for variable in list it duplicates div-->

  <ul>
    <li ng-repeat="item in list">
    <h2>Task: {{ item.thing }}</h2> 
    Edit: <input type="checkbox" ng-model="edit" aria-label="Toggle ngShow">
    <div ng-show="edit"> <input type="text" ng-model="item.thing"></div>
    Show description: <input type="checkbox" ng-model="check" aria-label="Toggle ngShow">
    <h3 ng-show="check"> Description: {{ item.description }} </h3>
    Edit: <input type="checkbox" ng-model="edit2" aria-label="Toggle ngShow">
    <div ng-show="edit2"><input type="text" ng-model="item.description"></div>
     <br><button ng-click="isdone(true, item)">Done</button>  <button ng-click="delete($index)">delete</button> 
    </li>
  </ul>

  </div>

<%= yield %>

</body>
</html>

toDo/app/views/things_to_dos/_form.html.erb
<%= form_for(@things_to_do) do |f| %>
  <% if @things_to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@things_to_do.errors.count, "error") %> prohibited this things_to_do from being saved:</h2>

      <ul>
      <% @things_to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thing %><br>
    <%= f.text_field :thing %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.text_field :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

toDo/app/views/things_to_dos/edit.html.erb
<h1>Editing Things To Do</h1>

<%= render 'form' %>

<%= link_to 'Show', @things_to_do %> |
<%= link_to 'Back', things_to_dos_path %>

toDo/app/views/things_to_dos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Things To Dos</h1>

<table>
  <thead>
    <tr>
      <th>Thing</th>
      <th>Done</th>
      <th>Default</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things_to_dos.each do |things_to_do| %>
      <tr>
        <td><%= things_to_do.thing %></td>
        <td><%= things_to_do.description %></td>
        <td><%= things_to_do.done %></td>
        <td><%= link_to 'Show', things_to_do %></td>
        <td><%= link_to 'Edit', edit_things_to_do_path(things_to_do) %></td>
        <td><%= link_to 'Destroy', things_to_do, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Things to do', new_things_to_do_path %>

toDo/app/views/things_to_dos/new.html.erb
<h1>New Things To Do</h1>

<%= render 'form' %>

<%= link_to 'Back', things_to_dos_path %>

toDo/app/views/things_to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thing:</strong>
  <%= @things_to_do.thing %>
</p>

<p>
  <strong>Description:</strong>
  <%= @things_to_do.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @things_to_do.done %>
</p>

<%= link_to 'Edit', edit_things_to_do_path(@things_to_do) %> |
<%= link_to 'Back', things_to_dos_path %>