Instacram/config/routes.rb
Rails.application.routes.draw do
  resources :photos

end

Instacram/app/models/photo.rb
require 'fileutils' 

class Photo < ActiveRecord::Base
  attr_accessor :file

  validates :format, inclusion: ['jpg','gif','png']

  before_validation do
      self.format = Rack::Mime::MIME_TYPES.invert[@file.content_type].gsub('.','')
  end


# activerecord callback
  after_save do
    # defining structure/location of path
    # copy temp file to permanent!
    path = Rails.root.join('public','photos', [id, self.format].join('.'))
    image = MiniMagick::Image.open(@file.path)
    # can use only one of these to allow it to keep the right aspect ratio
    image.resize "300x300"
    image.colorspace("Gray")
    image.write path
    # don't need this anymore since imagemagic is manipulating it?
    # FileUtils.mv(@file.path, path)
  end
end

Instacram/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    # raise "hold it!"

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :description, :file)
    end
end

Instacram/app/helpers/photos_helper.rb
module PhotosHelper
end

Instacram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instacram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Instacram/app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :file %><br>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

Instacram/app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

Instacram/app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Width</th>
      <th>Height</th>
      <th>Format</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.name %></td>
        <td><%= photo.description %></td>
        <td><%= photo.width %></td>
        <td><%= photo.height %></td>
        <td><%= photo.format %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

Instacram/app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

Instacram/app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<!-- image helper we added -->
<%= image_tag photo_path(@photo, @photo.format) %>


<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo.description %>
</p>

<p>
  <strong>Width:</strong>
  <%= @photo.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @photo.height %>
</p>

<p>
  <strong>Format:</strong>
  <%= @photo.format %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>